/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GitlabActivityRouteImport } from './routes/gitlab-activity'
import { Route as SplitbillRouteImport } from './routes/splitbill'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GitlabActivityRoute = GitlabActivityRouteImport.update({
  id: '/gitlab-activity',
  path: '/gitlab-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitbillRoute = SplitbillRouteImport.update({
  id: '/splitbill',
  path: '/splitbill',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gitlab-activity': typeof GitlabActivityRoute
  '/splitbill': typeof SplitbillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gitlab-activity': typeof GitlabActivityRoute
  '/splitbill': typeof SplitbillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gitlab-activity': typeof GitlabActivityRoute
  '/splitbill': typeof SplitbillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gitlab-activity' | '/splitbill'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gitlab-activity' | '/splitbill'
  id: '__root__' | '/' | '/gitlab-activity' | '/splitbill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GitlabActivityRoute: typeof GitlabActivityRoute
  SplitbillRoute: typeof SplitbillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gitlab-activity': {
      id: '/gitlab-activity'
      path: '/gitlab-activity'
      fullPath: '/gitlab-activity'
      preLoaderRoute: typeof GitlabActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splitbill': {
      id: '/splitbill'
      path: '/splitbill'
      fullPath: '/splitbill'
      preLoaderRoute: typeof SplitbillRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GitlabActivityRoute: GitlabActivityRoute,
  SplitbillRoute: SplitbillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
